### ISSUE TITLE
After deployment its not working

### ISSUE THREAD

**Issue by Aheri7** [bradtraversy/github-finder-app#4]
after deployment nothing loads and on console error is showing

Failed to load resource: the server responded with a status of 401 ()
createError.js:16 Uncaught (in promise) Error: Request failed with status code 401
    at e.exports (createError.js:16:15)
    at e.exports (settle.js:17:12)
    at XMLHttpRequest.E (xhr.js:66:7)

**Comment by bushblade** [comment]
Hi @Aheri7 
401 would be unauthorized.
This commonly happens if your push code to your Github repository for the project that contains your API access token.
If that happens then Github detect your token and revoke it for your security.
So check that you have your .env file listed in .gitignore or use .env.local instead, which is already ignored in a React app.
You will also need to clear git cache of the file so that it looks to the rules again, just adding a rule to your .gitignore doesn't stop tracking something you have previously been tracking so run...
`git rm --cached .env`
Then you can get a new access token and add, commit and push again without sharing your .env and access token.
I'll close as an issue here as this isn't a issue with the code base.
If you have further issues then please post in the Udemy Q&A and one of us will get to you.
